---
title: "SIMBRA"
image: images/simbra-symbol-circular.svg
about:
  template: jolla
  id: jolla-heading
  image-width: 22.5rem
  image-shape: round
  links:
    - icon: people-fill
      text: Sobre o Evento
      href: https://sobre.simbra.com.br
      target: _blank
    - icon: calendar-event-fill
      text: Programa
      href: https://programa.simbra.com.br
      target: _blank
    - icon: github
      text: GitHub
      href: https://github.com/simbra-org
      target: _blank
    - icon: instagram
      text: Instagram
      href: https://www.instagram.com/simbra_org/
      target: _blank
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/company/simbra-org
      target: _blank
    - icon: envelope-fill
      text: E-mail
      href: mailto:oi@simbra.com.br
      target: _blank
---

```{r}
#| label: Setup
#| include: false

library(here)
library(htmltools)

source(here("R", "_setup.R"))
```

::::{#jolla-heading}
::: {.about-jolla-subtitle}
```{=html}
<span style="display: inline-block;">
  1.º Simpósio Interdisciplinar Brasileiro<br class="responsive-break">
  de Modelos Baseados em Agentes
</span>
```
:::
::::

::::{.quarto-about-jolla .quarto-about-jolla-margin}
```{r}
#| eval: true
#| output: asis
#| echo: false

tags$hr(class = "about-sep")
```

[**Apoio**]{style="font-size: 1.25rem;"}

::: {style="margin-top: -1.5rem;"}
```{r}
#| echo: false

logos <- list(
  list(
    image = "images/sustentarea-logo.svg",
    height = "6rem",
    url = "https://www.fsp.usp.br/sustentarea",
    alt = "Sustentarea",
    first = TRUE
  ),
  list(
    image = "images/inct-logo.svg",
    height = "5.5rem",
    url = "https://www.fsp.usp.br/inct-combate-a-fome",
    alt = "INCT Combate à Fome",
    first = TRUE
  ),
  list(
    image = "images/usp-fsp-logo.png",
    height = "6rem",
    url = "https://www.fsp.usp.br",
    alt = "Faculdade de Saúde Pública (FSP)"
  ),
  list(
    image = "images/usp-each-logo.svg",
    height = "4.5rem",
    url = "https://www.each.usp.br",
    alt = "Escola de Artes, Ciências e Humanidades (EACH)"
  ),
  list(
    image = "images/usp-iee-logo.png",
    height = "7rem",
    url = "https://www.each.usp.br",
    alt = "Instituto de Energia e Ambiente (IEE)"
  ),
  # list(
  #   image = "images/usp-icmc-logo.svg",
  #   height = "5rem",
  #   url = "https://www.icmc.usp.br",
  #   alt = "Instituto de Ciências Matemáticas e de Computação (ICMC)"
  # ),
  list(
    image = "images/usp-mae-levoc-logo.svg",
    height = "5rem",
    url = "https://mae.usp.br/levoc/",
    alt = paste0(
      "Laboratório Interdisciplinar de Pesquisas em Evolução, ",
      "Cultura e Meio Ambiente (LEVOC)"
    )
  ),
  list(
    image = "images/usp-lapomed-logo.png",
    height = "6.5rem",
    url = "#",
    alt = "Laboratório de Pesquisa no Oriente Médio"
  ),
  # list(
  #   image = "images/usp-mae-logo.svg",
  #   height = "4rem",
  #   url = "https://mae.usp.br",
  #   alt = "Museu de Arqueologia e Etnologia (MAE)"
  # ),
  list(
    image = "images/usp-logo.svg",
    height = "3rem",
    url = "https://www.usp.br",
    alt = "Universidade de São Paulo (USP)"
  ),
  list(
    image = "images/ufpi-logo.png",
    height = "5rem",
    url = "https://www.ufpi.br",
    alt = "Universidade Federal do Piauí (UFPI)"
  ),
  list(
    image = "images/resiclima-logo.svg",
    height = "7rem",
    url = "https://resiclima.com.br",
    alt = "Rede Resiclima"
  ),
  # list(
  #   image = "images/ufpr-logo.svg",
  #   height = "5rem",
  #   url = "https://ufpr.br/",
  #   alt = "Universidade Federal do Paraná (UFPR)"
  # ),
  # list(
  #   image = "images/ipea-logo.svg",
  #   height = "3.5rem",
  #   url = "https://www.ipea.gov.br",
  #   alt = "Instituto de Pesquisa Econômica Aplicada (IPEA)"
  # ),
  list(
    image = "images/qub-logo.svg",
    height = "4.5rem",
    url = "https://www.qub.ac.uk",
    alt = "Queen's University Belfast (QUB)"
  ),
  list(
    image = "images/omf-logo.svg",
    height = "2.5rem",
    url = "https://www.openmodelingfoundation.org/",
    alt = "Open Modeling Foundation (OMF)"
  ),
  list(
    image = "images/comses-net-logo.png",
    height = "4.5rem",
    url = "https://www.comses.net",
    alt = "CoMSES Network"
  )
  # list(
  #   image = "images/capes-logo.svg",
  #   height = "5rem",
  #   url = "https://www.capes.gov.br",
  #   alt = "Coordenação de Aperfeiçoamento de Pessoal de Nível Superior (CAPES)"
  # ),
  # list(
  #   image = "images/fapesp-logo.svg",
  #   height = "5rem",
  #   url = "https://www.fapesp.br",
  #   alt = "FAPESP"
  # )
)
```

```{r}
#| echo: false
#| output: asis

div(
  style = "text-align: center;",
  logos |>
    lapply(
      function(i) {
        tags$span(
          tags$a(
            href = i$url,
            tags$img(
              src = i$image,
              alt = i$alt,
              style = paste0("height: ", i$height, "; ")
            ),
          ),
          style = paste0(
            "display: inline-block; ",
            "text-align: center; ",
            "margin-top: 1.5rem; ",
            "margin-left: 0.75rem; ", "",
            "margin-right: 0.75rem; ", ""
          )
        )
      }
    ) |>
      tagList() |>
      browsable()
)
```
:::
::::
